export const GET_PROJECTS_REQUEST = 'GET_PROJECTS_REQUEST';
export const GET_PROJECTS_REQUEST_SUCCESS = 'GET_PROJECTS_REQUEST_SUCCESS';
export const GET_PROJECTS_REQUEST_FAILURE = 'GET_PROJECTS_REQUEST_FAILURE';

export const GET_PROJECT_REQUEST = 'GET_PROJECT_REQUEST';
export const GET_PROJECT_REQUEST_SUCCESS = 'GET_PROJECT_REQUEST_SUCCESS';
export const GET_PROJECT_REQUEST_FAILURE = 'GET_PROJECT_REQUEST_FAILURE';
