export const FETCH_PROJECTS_REQUEST = 'FETCH_PROJECTS_REQUEST';
export const FETCH_PROJECTS_REQUEST_SUCCESS = 'FETCH_PROJECTS_REQUEST_SUCCESS';
export const FETCH_PROJECTS_REQUEST_FAILURE = 'FETCH_PROJECTS_REQUEST_FAILURE';

export const FETCH_PROJECT_REQUEST = 'FETCH_PROJECT_REQUEST';
export const FETCH_PROJECT_REQUEST_SUCCESS = 'FETCH_PROJECT_REQUEST_SUCCESS';
export const FETCH_PROJECT_REQUEST_FAILURE = 'FETCH_PROJECT_REQUEST_FAILURE';
