default: &default
  encoding: unicode
  adapter: postgresql
  pool: 5

development:
  <<: *default
  database: scoreboard_development

test: &test
  <<: *default
  database: scoreboard_test

production:
  <<: *default
  database: scoreboard_production
